# Generated by Django 3.0.6 on 2020-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_periods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
